const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const envPath = path.resolve(rootDir, '.env');
const outputPath = path.resolve(rootDir, 'src', 'environments', 'environment.generated.ts');

const parseEnvFile = (filePath) => {
  if (!fs.existsSync(filePath)) {
    return {};
  }

  return fs
    .readFileSync(filePath, 'utf8')
    .split(/\r?\n/)
    .filter((line) => line.trim() && !line.trim().startsWith('#'))
    .reduce((acc, line) => {
      const [key, ...rest] = line.split('=');

      if (!key) {
        return acc;
      }

      acc[key.trim()] = rest.join('=').trim();
      return acc;
    }, {});
};

const fileEnv = parseEnvFile(envPath);

const readEnv = (key) => {
  const value = process.env[key] || fileEnv[key] || '';
  return value.trim();
};

const supabaseUrl = readEnv('SUPABASE_URL');
const supabaseAnonKey = readEnv('SUPABASE_ANON_KEY');

const missingKeys = [
  ['SUPABASE_URL', supabaseUrl],
  ['SUPABASE_ANON_KEY', supabaseAnonKey]
]
  .filter(([, value]) => !value)
  .map(([key]) => key);

if (missingKeys.length > 0) {
  throw new Error(
    `Missing required Supabase environment variables: ${missingKeys.join(', ')}. ` +
      'Define them in .env locally or in Vercel Environment Variables.'
  );
}

const generatedContent = `// This file is generated by scripts/generate-env.js.
// Do not edit manually.
export const generatedEnvironment = {
  supabaseUrl: ${JSON.stringify(supabaseUrl)},
  supabaseAnonKey: ${JSON.stringify(supabaseAnonKey)}
};
`;

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, generatedContent);

console.log('Generated Angular Supabase environment from SUPABASE_URL and SUPABASE_ANON_KEY.');
